### ISSUE TITLE
Building ARM images and nodejs

### ISSUE THREAD

**Issue by jgato** [resin-os/resin-qemu#16]
Hi there,

I have been following your article about "Building ARM containers on any x86 machine, even DockerHub", and I have to say it is really great. I will try this in our CI workflow to create Intel and ARM images.

In a first try everything went ok building arm image but it failed about nodejs commands:

```
Step 7 : RUN npm install
 ---> Running in 906dd41d7ca5

/usr/share/npm/node_modules/npmconf/config-defs.js:322
  Object.keys(os.networkInterfaces()).map(function (nic) {
                 ^
Error: EAFNOSUPPORT, address family not supported
    at getLocalAddresses (/usr/share/npm/node_modules/npmconf/config-defs.js:322:18)
    at Object.<anonymous> (/usr/share/npm/node_modules/npmconf/config-defs.js:269:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/share/npm/node_modules/npmconf/npmconf.js:4:18)
    at Module._compile (module.js:456:26)

```

What could be the issue? I have seen there is a repo with node-arm, could it be related? Previous commands (apt, copys...) built ok.

regards,

**Comment by petrosagg** [comment]
This is a limitation of qemu user-mode emulation. It's fixed with this patch https://github.com/resin-io/qemu/commit/313be808b8b070aa1db89bdc81b39edcf8153893

**Comment by petrosagg** [comment]
You can use the prebuilt binary from here https://github.com/resin-io/qemu/releases/tag/2.5.0-resin-rc3

**Comment by jgato** [comment]
But I am using the binary that came with your image resin/armv7hf-debian-qemu, should I include the binary manually?

**Comment by petrosagg** [comment]
@jgato I updated the binary in the image, if you `docker pull` the latest tag it should have the right binary

**Comment by petrosagg** [comment]
If you have any other issues you can open them on this repo https://github.com/resin-io-projects/armv7hf-debian-qemu because this one is about something else
