### ISSUE TITLE
Squashfs

### ISSUE THREAD

**Issue by splitice** [resin-os/resin-qemu#87]
While the Raspberry PI and similar OS's have SquashFS enabled in the kernel options Resin OS 2.12.5+rev1 Qemu images do not.

```
zcat /proc/config.gz | grep SQUAS
# CONFIG_SQUASHFS is not set
```

For those of use using QEMU applications to develop and test our applications for our hardware platforms it would be useful to have this kernel option enabled.

**Comment by agherzan** [comment]
Thanks, @splitice for the report. What is your use-case of using this filesystem?

**Comment by splitice** [comment]
We are currently looking into it as a method of reducing the cost of delta upgrades. Our containers have nearly 100k files due to the usage of high level languages with quite a number of files in their structure.

Reducing the upgrades to comparing the contents of a single file in place of thousands has (under preliminary analysis) led to improvements in the upgrade process both in time and memory usage.

**Comment by agherzan** [comment]
I see. I don't see any reason not to include it in qemu builds. @splitice would you be willing to push a PR for this? It should be similar to what we already have [here](https://github.com/resin-os/resin-qemu/blob/master/layers/meta-resin-qemu/recipes-kernel/linux/linux-yocto_%25.bbappend#L3).

**Comment by floion** [comment]
Fixed by https://github.com/resin-os/resin-qemu/pull/93
