### ISSUE TITLE
Aufs crashes

### ISSUE THREAD

**Issue by splitice** [resin-os/resin-qemu#88]
Sometimes the QEMU vm's crash on disk activity. The error is:

```
[319774.859040] auplink[3849]: segfault at 7ffdf73427b8 ip 0000000000439079 sp 00007ffdf73427c0 error 6 in auplink[400000+b9000]
````

This appears to be due to a bug in AUFS tools that has been patched for a few years (documented here: https://github.com/moby/moby/issues/10595 & https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=777559). The QEMU VM is using version 20150323 whereas it's fixed around 20160919

**Comment by floion** [comment]
Hi,
thanks for the report.
We'll look into this for the next release

**Comment by nmajin** [comment]
Any idea if the next release can be released right now? It appears to be ready to go. If not, any way for a workaround?

**Comment by floion** [comment]
Hi,
this will be in the next release v2.14.1+rev1

**Comment by floion** [comment]
Should be done today

**Comment by floion** [comment]
Hi. Version 2.14.3+rev1 was released. This has switched from aufs to overlay2 as docker backend storage driver.
Please let us now if you encounter any other issues
